# Generated by Django 3.2.8 on 2021-11-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20211110_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettype',
            options={'ordering': ('assettype_pk',)},
        ),
        migrations.AlterModelOptions(
            name='comp',
            options={'ordering': ('-deployed_date',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('region_pk',)},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('station_pk',)},
        ),
    ]
