
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('', views.index, name='home'),
    path("register/", views.register, name = 'register'),
    # path("change_password/", views.change_password, name = 'change_password'),
    path('result/', views.result, name='result'),
    path('deployment_old/',views.old, name='deployment_old'),
    path('live_search/',csrf_exempt(views.live_search), name='live_search'),
    path('asset_type/',views.load_assettype, name='asset_type'),
    path('region/',views.load_region, name='region'),
    path('station/',views.load_station, name='station'),
    path('live_mac/',csrf_exempt(views.live_mac), name='live_mac'),
    path('client_accept/',views.client_accept, name='client_accept'),
    path('hod_accept/',views.hod_accept, name='hod_accept'),
    path('approve/', views.approve, name='approve'),
    path('approveresult/', views.approveresult, name='approveresult'),
    path('ict_approval/', views.ict_approve, name='ict_approval'),
    path('ict_reject/', views.ict_reject, name='ict_reject'),
    path('asset_edit/', views.edit_home, name='asset_edit'),
    path('edit_view/', views.edit_view, name='edit_view'),
    path('edit_back/', views.edit_back, name='edit_back'),
    path('relocate/', views.relocate, name='relocate'),
    path('rel/', views.rel, name='rel'),
    path('rel_back/', views.rel_back, name='rel_back'),
    path('monitor/', views.monitor, name='monitor'),
    path('monitor_details/', views.details, name='monitor_details'),
    path('monitor_change/', views.monitor_change, name='monitor_change'),
    path('ownership/', views.search, name='ownership_search'),
    path('change_ownership/', views.change, name='ownership_change'),
    path('change_back/', views.change_back, name='change_back'),
    path('surrender/', views.surrender, name='surrender'),
    path('surrender_back/', views.surrenderback, name='surrenderback'),
    path('sur_backend/', views.sur_backend, name='sur_backend'),
    path('obsolete/', views.obso, name='obsolete'),
    path('obsolete_back/', views.obsoback, name='obsoleteback'),
    path('obso_backend/', views.obso_backend, name='obso_backend'),
    path('asset_repairs/', views.repairs, name='asset_repairs'),
    path('asset_result/', views.result_repairs, name='asset_result'),
    path('repair_register/', views.repair_register, name='repair_register'),
    path('repair_release/', views.repair_release, name='release'),
    path('return_repair/', views.return_repair, name='return_repair'),
    path('deploy_report/', views.deploy_report, name='deploy_report'),
    path('deploy_result/', views.deploy_result, name='deploy_result'),
    path('user_search/', views.user, name='user_search'),
    path('user_assets/', views.user_report, name='user_assets'),
    path('history/', views.history, name='history'),
    path('history_report/', views.history_report, name='history_report'),
    path('asset_search/', views.asset_search, name='asset_search'),
    path('asset_report/', views.asset_report, name='asset_report'),
    path('excel_export/', views.excel_export, name='excel_export'),
    path('free_search/', views.free_search, name='free_search'),
    path('free_report/', views.free_report, name='free_report'),
    path('obso_search/', views.obso_search, name='obso_search'),
    path('obso_report/', views.obso_report, name='obso_report'),
    
    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name="asset/accounts/password_reset.html"),
     name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="asset/accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="asset/accounts/password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="asset/accounts/password_reset_done.html"), 
        name="password_reset_complete"),
]
